- src/Core/Api/Services/FetchDocumentService.php
Increases the timeout for the cURL client in `FetchDocumentService` from 10 seconds to 30 seconds.
This lowers the chance of a timeout event while getting labels and/or packing slips.
This is a provisional step in resolving https://github.com/wayfair-contribs/plentymarkets-plugin/issues/10
> set timeout in FetchDocumentService to 30 seconds

- angular/package-lock.json
Remove security alert about updating `minimist` to 0.2.1 or later, by rebuilding the node packages after some targeted removals.
> bump minimist to 1.2.5

- src/Core/Api/Services/FetchDocumentService.php
**Ticket:** EM-58
For validating document URLs In FetchDocumentService, switch from a case-sensitive "contains" check to a case-insensitive "starts-with" check.
> EM-58: use a case-insensitive starts-with for URL check

- src/Core/Helpers/AbstractConfigHelper.php
- src/Helpers/ConfigHelper.php
- src/Services/LoggingService.php
To make it easier on developer to address bug fixes made by suppliers Wayfair plugin version has been added to the PlentyMarkets logs generated by the Wayfair plugin.
>  Adding plugin version to logs

- meta/documents/user_guide_en.md
Weird characters at the beginning of the English user guide were ruining the Markdown formatting
> remove chars at beginning of English user guide

- src/Core/Api/APIService.php
- change constant from `LOK_KEY_API_SERVICE` to `LOG_KEY_API_SERVICE`
> Blocker: APIService module does not compile

- src/Core/Api/Services/InventoryService.php
As we need to do "chunked" inventory feeds, even for "full inventory," we cannot use `TRUE_UP` for the `feedKind` as `TRUE_UP` implies that it contains ALL inventory for all items.
This change will force all inventory feeds to have the `DIFFERENTIAL` value for `feedKind`.
> make all inventory saves use DIFFERENTIAL for feedKind

- src/Repositories/KeyValueRepository.php
The `KeyValueRepository` is restricting saving `false` or the empty string, but these are legitimate states of things in the plugin.
The full inventory service sometimes breaks when trying to mark the "success" flag to `false`, and this should clear that up.
> allow saving false or empty values

- src/Core/Api/Services/FetchOrderService.php
Fetch Order Service was eating Exceptions and had a syntax error in the code where it did so.
> remove try catch when Fetching orders

- src/Mappers/InventoryMapper.php
fix a comparison that was marking inventory amounts of `0` as invalid
> allow inventory amounts of zero to be sent to wayfair

- src/Services/ShipmentRegisterService.php
* Remove member variable `registerResult` due to risky side-effects / race conditions
* being used as a local variable in some contexts, as a member variable in others
* was cleared out when calling some functions
* (de)registration for one set of POs could impact (de)registration for other POs
* Remove unused member variable `warehouseSupplierRepository`
* Remove unneeded `WarehouseSupplierRegistry` import (as `warehouseSupplierRepository` was removed)
> remove junk code from ShipmentRegisterService

- src/Services/OrderPropertyService.php
- src/Services/SaveOrderDocumentService.php
- src/Services/ShipmentRegisterService.php
Repair bugs to enable Shipment Registration
- Remove usage of `OrderPropertyRepositoryContract`.
- Per Plentymarkets:"You don’t get all properties of an order from the order property repository. Use the Order repository and access the properties on the Order."
- See https://forum.plentymarkets.com/t/adding-shipping-information-to-an-order/598381/11
- Use `findOrderByExternalOrderId` instead of doing a manual search + browse of Orders (which was failing!)
- Add details to logs, to help @jathmel verify ASN behaviors
> use Order contract to get properties

- src/Services/ShipmentRegisterService.php
It's okay to have one tracking number for multiple shipments on the same Order. Our logs should reflect that. This new log was introduced after the last official release.
(Checks are already in place for a lack of tracking number).
> change log level for "amount of packages does not match amount of shipping labels" to debug

- README.md
- meta/documents/user_guide/en/initial_setup.md
- meta/documents/user_guide/en/obtaining_credentials.md
- meta/documents/user_guide/en/plugin_installation.md
- meta/documents/user_guide/en/settings_guide.md
- meta/documents/user_guide/en/test_mode.md
- meta/documents/user_guide/en/tips_and_tricks.md
- meta/documents/user_guide/en/updating.md
- meta/documents/user_guide/en/wayfair_shipping.md
- meta/documents/user_guide_en.md
Making the User Guide that shows up on the PlentyMarketplace something that's enjoyable and easy to read.
**Notices:**
- The link at the top points to the `master` branch version of this document, so that people reading stale versions on the PlentyMarketplace can come read the current information
- **We will be adding screenshots to the documentation in future Pull Requests, and suppliers will see them because they'll be reading the docs on GitHub, not on Plentymarkets!!!**
- We must use Fully-Qualified URLs for images and links in `meta/documents/user_guide_en.md`, because the PlentyMarketplace copies ONLY the `meta/documents/user_guide_en.md` file and the other documents and images do not get hosted there. 
- Most of the links in the main document will NOT work until this PR gets …
> refactor the ENG user guide to link-out to github for all information

- README.md
Add the german marketplace link.
Note: this readme does NOT ship with the plugin. It is only for people who come to our repo, which is the second hit on google.
> fix marketplace links in repo's readme

- meta/documents/user_guide/en/initial_setup.md
the initial setup document was using a Fully-Qualified link instead of a relative link, but the context does not require the Fully-Qualified link.
> use a relative link to settings page

- angular/package-lock.json
- angular/package.json
- angular/src/app/assets/lang/locale-de.json
- angular/src/app/assets/lang/locale-en.json
- plugin.json
- ui/assets/lang/locale-de.json
- ui/assets/lang/locale-en.json
Now that `release-1.1.2` is branched off of `master`, the `master` branch should be considered `1.1.3-alpha`
> bump plugin version to 1.1.3-alpha

- meta/documents/user_guide/en/initial_setup.md
The initial setup guide failed to mention the `Send all inventory items to Wayfair` setting early enough.
> Mention "all items" setting during setup

- meta/documents/user_guide/en/updating.md
fix a broken image link in the updating document, found by @jathmel while he made the german screenshots
> fix image link for updating plugin

- angular/package-lock.json
- angular/package.json
- angular/src/app/assets/lang/locale-de.json
- angular/src/app/assets/lang/locale-en.json
- meta/documents/changelog_de.md
- meta/documents/changelog_en.md
- plugin.json
- ui/assets/lang/locale-de.json
- ui/assets/lang/locale-en.json
As the `release-1.1.3` branch now exists, the `main` branch will report itself as version `1.1.4-alpha`.
> set main branch version identifier to be 1.1.4-alpha

- src/Services/CreateOrderService.php
- src/Services/SavePackingSlipService.php
- a lack of packing slip no longer throws an exception
- an order is no longer considered flawed due to lack of packing slip data - no longer will appear as "failed" in logs sent to Wayfair.
> avoid throwing exceptions for lack of packing slips

- angular/package.json
make typescript linting functional on Windows
There are MANY issues that appeared when the linter ran in linux, making the draft "build UI" GitHub action fail!
> remove arg from tslint call so that it executes correctly

- .github/workflows/build_ui.yml
When a developer pushes changes to the `angular` or `ui` directories, GitHub will rebuild the UI to make sure it is up to date, and automatically push a new commit.
> have GitHub rebuild the UI when needed

- .github/workflows/build_ui.yml
- use `git status -s` to check if UI is up to date
- Fail out of the UI building action if there are changes to be made but the branch is protected (main, release, etc), because that means nobody has actually seen/tested the UI yet (and because the bot is not able to push the generated UI)
> improved UI Builder action

- src/Controllers/InventoryController.php
- src/Services/InventoryUpdateService.php
- When AuthException is caught during Inventory Sync, return an 401 (unauthorized) because the plugin is not authorized to work with Wayfair (yet). (Was previously a 400).
- Return an HTTP 500 when a non-Auth issue occurs during Inventory Sync (was previously a 400).
> return the correct HTTP error codes for Inventory

- .github/workflows/build_ui.yml
Adds a clause to the "is protected" condition in order to prevent the GitHub action that rebuilds the `ui` folder from attempting to do a check-in when a tag is created
> don't let UI builder try to check-in on a tag

- src/Mappers/InventoryMapper.php
- tests/php/Mappers/InventoryMapperTest.php
Plentymarkets may report a non-integer amount for stock.
This PR rounds the `netStock` in a Warehouse **down** to the nearest integer.
Needs @mcloughlin77 to look at this from a Wayfair Inventory standpoint before we can proceed.
> round floating point stock amount DOWN to nearest integer

- src/Mappers/InventoryMapper.php
- tests/php/Mappers/InventoryMapperTest.php
Fixes https://github.com/wayfair-contribs/plentymarkets-plugin/issues/194
The `updatedAtFrom` and `updatedAtTwo` filters are currently applied to the `StockRepositoryContract` used for **calculating** inventory amounts for periodic inventory synchronizations, causing the Wayfair plugin to send the inventory amount(s) only for the Warehouse(s) that changed.
**If only one warehouse had a change for the item, the item will go out of stock until the next change in stock!**
The Wayfair plugin should be sending an up-to-date calculation of **ALL** inventory for the item, in **ALL** Warehouses where it appears.
The timestamp filters should only be used to **detect** if the stock amounts for the Variation has experienced any changes.
This PR introduces a `hasInventoryChanged` helper function …
> Use time filters only for stock CHANGE detection - do not filter out Warehouses from inventory sync

- .github/workflows/php_test.yml
- composer.json
**BLOCKS ALL SUBSEQUENT PRs**
Ubuntu 16.04 image on GitHub is using PHP 8.0 by default, so the test script needs to switch the OS over to PHP 7.0 before doing any `Composer` / `PHP` actions.
The `dev-beta7` channel of the `plentymarkets/plugin-interface` package now depends on PHP 7.3, so the requirement has been updated to the `dev-stable7` channel, which is still compatible with PHP 7.0.
The Composer Cache step has been **removed**, as it was preventing us from detecting PHP/Composer issues.
> repair test scripts by enforcing use of php 7.0 and stable Plenty API definitions, don't use composer cache

- .github/workflows/php_test.yml
- src/Core/Api/Services/LogSenderService.php
- src/Core/Contracts/LoggerContract.php
- src/Cron/FullInventorySyncCron.php
- src/Cron/InventorySyncCron.php
- src/Cron/OrderAcceptCron.php
- src/Cron/OrderImportCron.php
- src/Models/InventoryUpdateResult.php
- src/Repositories/WarehouseSupplierRepository.php
- src/Services/InventoryStatusService.php
- src/Services/InventoryUpdateService.php
- src/Services/LoggingService.php
- tests/php/Services/InventoryUpdateServiceTest.php
- tests/php/lib/TestTimeLogger.php
- tests/php/lib/plentymockets/Factories/VariationDataFactory.php
Mitigating https://github.com/wayfair-contribs/plentymarkets-plugin/issues/204 where a supplier's inventory synchronization process is stuck at the first attempt to upload all inventory to Wayfair.
**This will NOT solve/mitigate all of the underlying causes of failed/stalled Inventory Syncs,** as those are by yet undiscovered issues in the Wayfair Plugin code and/or they are the result of limitations placed on the Wayfair Plugin by the Plentymarkets system.
- Set inventory sync state in the database to `IDLE` immediately after detecting a stale/stalled Inventory Sync, to avoid letting the stale/stalled run block any subsequent runs.
- The partial inventory cron job that runs every 15-30 minutes will do this
- The change in state will allow the UI to do a "manual" full sync within 1 hour …
> prevention and recovery for stuck inventory sync 
